{"name": "test_dailure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_dailure():\n>       assert False\nE       assert False\n\ntestdemo\\python-allure使用.py:7: AssertionError"}, "start": 1635060717552, "stop": 1635060717553, "uuid": "8f51807d-a991-427c-953a-e6b2adc8befe", "historyId": "197969cbebcfe799a3fa71d4ddf7b596", "testCaseId": "5e608cfaecdae05fec34a45223a6ff7e", "fullName": "testdemo.python-allure使用#test_dailure", "labels": [{"name": "parentSuite", "value": "testdemo"}, {"name": "suite", "value": "python-allure使用"}, {"name": "host", "value": "010A05050057"}, {"name": "thread", "value": "2256-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testdemo.python-allure使用"}]}